'------------------------------------------------------------------------------
'  <auto-generated>
'      此代码由编码的 UI 测试生成器生成。
'      版本: 12.0.0.0
'
'      如果重新生成代码，则更改此文件可能会导致错误的行为，
'      并将丢失这些更改。
'  </auto-generated>
' ------------------------------------------------------------------------------

Imports System
Imports System.CodeDom.Compiler
Imports System.Collections.Generic
Imports System.Drawing
Imports System.Text.RegularExpressions
Imports System.Windows.Input
Imports Microsoft.VisualStudio.TestTools.UITest.Extension
Imports Microsoft.VisualStudio.TestTools.UITesting
Imports Microsoft.VisualStudio.TestTools.UnitTesting
Imports Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard
Imports Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse
Imports MouseButtons = System.Windows.Forms.MouseButtons

Namespace CodedUITestProject1
    
    <GeneratedCode("编码的 UI 测试生成器", "12.0.21005.1")>  _
    Partial Public Class UIMap
    End Class
End Namespace
